[package]
name = "bitview_plugin_distribution"
description = "The UTXO distribution plugin for Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true

[dependencies]
bitview_transforms = { workspace = true }
bitview_collections = { workspace = true, features = ["storage"] }
bitview_vecs = { workspace = true }
brk_exit = { workspace = true }
bitview_compute = { workspace = true }
bitview_plugin = { workspace = true }
bitview_plugin_mappings = { workspace = true }
bitview_plugin_inputs = { workspace = true }
bitview_plugin_outputs = { workspace = true }
bitview_plugin_price = { workspace = true }
bitview_plugin_transactions = { workspace = true }
bitview_cohort = { workspace = true, features = ["storage"] }
brk_error = { workspace = true, features = ["vecdb"] }
bitview_plugin_indexer = { workspace = true }
brk_oracle = { workspace = true }
bitview_traversable = { workspace = true }
brk_types = { workspace = true, features = ["storage"] }
derive_more = { workspace = true }
rayon = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }
vecdb = { workspace = true }

[dev-dependencies]
brk_reader = { workspace = true }
brk_rpc = { workspace = true }
tempfile = { workspace = true }
